// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCgy6xSme0gLoacrmcVr1XpLYI9Q_Cmww',
    appId: '1:647395303170:web:ccfa9990b64e7c498bac1b',
    messagingSenderId: '647395303170',
    projectId: 'fayoum-queue',
    authDomain: 'fayoum-queue.firebaseapp.com',
    storageBucket: 'fayoum-queue.firebasestorage.app',
    measurementId: 'G-763C2LFYBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8bxS_pJ40ftwSINqliDROEMnN0jY8wa4',
    appId: '1:647395303170:android:4e44d2eacaac9e9b8bac1b',
    messagingSenderId: '647395303170',
    projectId: 'fayoum-queue',
    storageBucket: 'fayoum-queue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZixOspfdrpeMdpfR-Tm8DWi4BHeV3U98',
    appId: '1:647395303170:ios:b20762fc1eb1f05a8bac1b',
    messagingSenderId: '647395303170',
    projectId: 'fayoum-queue',
    storageBucket: 'fayoum-queue.firebasestorage.app',
    iosBundleId: 'com.fayoum.fayoumStudentQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZixOspfdrpeMdpfR-Tm8DWi4BHeV3U98',
    appId: '1:647395303170:ios:b20762fc1eb1f05a8bac1b',
    messagingSenderId: '647395303170',
    projectId: 'fayoum-queue',
    storageBucket: 'fayoum-queue.firebasestorage.app',
    iosBundleId: 'com.fayoum.fayoumStudentQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCgy6xSme0gLoacrmcVr1XpLYI9Q_Cmww',
    appId: '1:647395303170:web:c7353f5d2cdaaa388bac1b',
    messagingSenderId: '647395303170',
    projectId: 'fayoum-queue',
    authDomain: 'fayoum-queue.firebaseapp.com',
    storageBucket: 'fayoum-queue.firebasestorage.app',
    measurementId: 'G-5SD4EF726F',
  );
}
